spring:
  application:
    name: Bugs Service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bugs
    username: postgres
    password: postgres
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
